<?php


// $ch = curl_init();

// curl_setopt($ch, CURLOPT_URL, "https://api.mixin.one/users");
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
// curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"full_name\":\"Bot User\",\"session_secret\":\"MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDMTuli9K9k7F+L7Rq34se23nQeV2yvjVGCZyRTbp8qNASnRq6N679ZflgVxNUsr2qkHN4eqvafrQ9IIcRXfofMlWWIU6MrgVVD0UEVyH4jKA5gUr4smU/SDnVLqb3TojYMELIKHgqnrjqDJ0b+vMUG1Iix4fi+CvjSiJzsWPOavQIDAQAB\"}");
// curl_setopt($ch, CURLOPT_POST, 1);

// $headers = array();
// $headers[] = "Content-Type: application/json";
// $headers[] = "Authorization: Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhaWQiOiI2MTc3NTUzNC00NzhhLTRhNmItOTA2My05ZWUzZTlmM2IwMzkiLCJleHAiOjE1NzY4ODU3NTMsImlhdCI6MTU0NTM0OTc1MywiaXNzIjoiYjQyN2QxMGUtNWNjMS00MDA0LTllM2QtMGY3MThiMDVhZTM5In0.SOWE8pGUuOaN6h7gaKd8m3IbbGuOAWUpDI5GkmckE1RqCJFtFzUNUSEcWDtsHfC4psYc1o2WYJkg6Qcpf3QpDpTZu976iWdm0cYBZPmB5e2jJG1AbL-f6h8gpG66bMKBIXkoQrTwEHTbu3iIIWdJxjETPViIPd86ukZ6N8R6lVA";

// curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);


// $result = curl_exec($ch);
//  print_r($result);
// if (curl_errno($ch)) {
//     echo 'Error:' . curl_error($ch);
// }
// echo "account created successfully";
// curl_close ($ch);


// include('vendor/rmccue/requests/library/Requests.php');
// Requests::register_autoloader();
// $headers = array(
//     'Content-Type' => 'application/json',
//     'Authorization' => 'Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhaWQiOiI3ZDVjOWU3MC1mZTkwLTRlYjUtYWRmZS0zZjBhZDI2NTdlODMiLCJleHAiOjE1NzY4ODczNzQsImlhdCI6MTU0NTM1MTM3NCwiaXNzIjoiMGEzZTM3Y2UtZTQ4MC00YzZiLWEwYmQtZTE4NmRmYmZiMzk3In0.SF0LbsN1TRO_VaqIGizerkcO-HqI7SLJEapso3FxwnOQV3oBD4gG2EyGAV1CaGD2u6chs_0f5LbvhmThgTG1g44E6pCmXUR9_PHw-XgROxdFCi9fnjFDaTo2BWNMcqTglmISBFyWE7q24HXR5u9O8Astwtp-br2iGtL6rB4KBd8'
// );
// $response = Requests::get('https://api.mixin.one/me', $headers);
// print_r($response);


// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.mixin.one/me");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");


$headers = array();
$headers[] = "Content-Type: application/json";
$headers[] = "Authorization: Bearer eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJhaWQiOiIyNWViM2U0Ny0xY2FjLTQxYjItOTdlMi04NThlYzI0ZjVjZDAiLCJleHAiOjE1NzY4ODc5NTQsImlhdCI6MTU0NTM1MTk1NCwiaXNzIjoiMGEzZTM3Y2UtZTQ4MC00YzZiLWEwYmQtZTE4NmRmYmZiMzk3In0.sNgRb8O7g4C_SGuKQW234YRtAJy_Na_J1JtQm-nsj0MaXDmBxojPVdCW38h8LG4lkShg_9WsnUSdm1q0OgDHZ3AFJoxBxbOJfda52cRLVXpMOWY4AbLTNMP4xfa_TBhC-YFLep4vAnIdD8snS8gkxqK5UugiP7LEubOOXhNuaLU";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
$data=$result;
extract(json_decode($data, true));

extract($data);
echo "\$user_id : $user_id; <br> \$identity_number : $identity_number; <br> \$full_name : $full_name;<br> \$session_id : $session_id; <br> \$code_id : $code_id;<br> \$code_url : $code_url";



if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);



?>